spring:
  datasource:
    url: jdbc:postgresql://url_de_staging/crud-db
    username: admin
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org:
      springframework:
        data: INFO
