spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crud-db
    username: admin
    password: 1234
  jpa:
      properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      springframework:
        data: DEBUG
